version: 0.1

phases:
  install:
   runtime-versions:
      nodejs: latest
  pre_build:
    commands:
      - echo installing dependencies...
      - npm i -g @angular/cli
      - npm install
  build:
    commands:
      # - echo testing...
      # - echo building...
      - ls -a
      - ng build 
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: dist/gradeapp
